//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OD.Data
{
    using System;
    using System.Collections.Generic;
    using ClientAppOD.CustomModels;

    public partial class MenuToppingsGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuToppingsGroup()
        {
            this.MenuToppings = new HashSet<MenuTopping>();
        }
    
        public int ID { get; set; }
        public string ToppingsGroup { get; set; }
        public string ToppingsGoupDisplayName { get; set; }
        public int StoreID { get; set; }
    
        public virtual Store BusinessDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuTopping> MenuToppings { get; set; }
    }
}
