//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OD.Data
{
    using System;
    using System.Collections.Generic;
    using ClientAppOD.CustomModels;

    public partial class MenuDishPropertiesGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuDishPropertiesGroup()
        {
            this.MenuDishProperties = new HashSet<MenuDishProperty>();
        }
    
        public int ID { get; set; }
        public string DishPropertyGroup { get; set; }
        public string DishPropertyPriceType { get; set; }
        public bool DishPropertyRequired { get; set; }
        public string DishPropertyGroupDisplayName { get; set; }
        public int BusinessDetailID { get; set; }
    
        public virtual Store BusinessDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuDishProperty> MenuDishProperties { get; set; }
    }
}
