//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTopping
    {
        public int ID { get; set; }
        public string Topping { get; set; }
        public Nullable<double> ToppingPrice { get; set; }
        public int MenuToppingsGroupID { get; set; }
    
        public virtual MenuToppingsGroup MenuToppingsGroup { get; set; }
        public int Selected { get; set; }
    }
}
