//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OD.Data
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.MenuItemModels = new HashSet<MenuItemModel>();
            this.MenuItemProperties = new HashSet<MenuItemProperty>();
            this.OrderItems = new ObservableCollection<OrderItem>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Vegetarian { get; set; }
        public Nullable<short> Spicyness { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Photo { get; set; }
        public string AllowToppings { get; set; }
        public string DishPropertyGroupId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public int MenuCategoryID { get; set; }
        public string DiscountOff { get; set; }
        public bool ItemSelected { get; set; }
        public virtual MenuCategory MenuCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItemModel> MenuItemModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItemProperty> MenuItemProperties { get; set; }
        public virtual ObservableCollection<OrderItem> OrderItems { get; set; }
    }
}
