//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OD.Data
{
    using System;
    using System.Collections.Generic;
    using ClientAppOD.CustomModels;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string DeliveryType { get; set; }
        public string DeliveryTime { get; set; }
        public string PaymentType { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public string SessionId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string Notes { get; set; }
        public string ResponceFromPrinter { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string CancelledBy { get; set; }
        public string CancelledReason { get; set; }
        public Nullable<System.DateTime> AcknowledgedDate { get; set; }
        public string DeliveredDate { get; set; }
        public bool Cancelled { get; set; }
        public bool Acknowledged { get; set; }
        public bool OutForDelivery { get; set; }
        public Nullable<decimal> VoucherCodeDiscount { get; set; }
        public string VoucherCode { get; set; }
        public bool Printed { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<decimal> CardFee { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public int BusinessDetailID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Status { get; set; }
        public string ClientIP { get; set; }
        public bool ValidForLoyality { get; set; }
        public string OrderText { get; set; }
        public string DiscountPercentage { get; set; }
        public string SagePayAuth { get; set; }
        public Nullable<System.DateTime> SupportAcknowledgedAt { get; set; }
        public virtual Store BusinessDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
