//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItem()
        {
            this.OrderModels = new HashSet<OrderModel>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Qta { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Total { get; set; }
        
        public int OrderID { get; set; }
        public int MenuItemId { get; set; }
        public Nullable<int> MenuItemPropertyId { get; set; }
        public string ItemType { get; set; }
        public string Name { get; set; }
        public string OrderText { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderModel> OrderModels { get; set; }
        public virtual Order Order { get; set; }
    }
}
